#pragma once

#ifndef EBONESID_HPP
#define EBONESID_HPP

enum EBonesID {

	BONE_BIP01 = 0x0,
	BONE_SPINE = 0x1,
	BONE_SPINE2 = 0x2,
	BONE_SPINE3 = 0x3,
	BONE_HEAD = 0x4,
	BONE_EYE_R = 0x5,
	BONE_EYE_L = 0x6,
	BONE_WEAPON = 0x7,
	BONE_FOOT_R = 0x8,
	BONE_FOOT_L = 0x9,
	BONE_ARM_R = 0xA,
	BONE_ARM_L = 0xB,
	BONE_CALF_R = 0xC,
	BONE_CALF_L = 0xD,
	BONE_CAMERA = 0xE,
	BONE_ID_NUM = 0xF,
};

#endif // !EBONESID_HPP